### ISSUE TITLE
Profile page error

### ISSUE THREAD

**Issue by Saranya-Ramesh-27** [fssa-batch3/deepika.sriram__web_project#11]
### Description of issue
In readme file, it is mentioned that click on edit profile option it will move to edit profile page but there is no edit profile option and I can directly edit my profile in profile page itself.

```
Path:      /pages/other%20pages/patient/patient%20profile%20page.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 884 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--rapid-doctor.netlify.app%2Fpages%2Fother%2520pages%2Fpatient%2Fpatient%2520profile%2520page.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x884&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--rapid-doctor.netlify.app/pages/other%20pages/patient/patient%20profile%20page.html)

**Comment by deepikasrm5** [comment]
I modifed the readme file regarding this. Please check it

**Comment by Saranya-Ramesh-27** [comment]
Clear.
