### ISSUE TITLE
Appointment detail page issue

### ISSUE THREAD

**Issue by Saranya-Ramesh-27** [fssa-batch3/deepika.sriram__web_project#12]
### Description of issue

In readme file to delete the appointment, it is mentioned that click on delete appointment button. There is no delete appointment button in the page. Correct the readme file there is delete history button.

```
Path:      /pages/other%20pages/patient/history%20details%20form.html?appointment-id=fc291eee-e94a-4ab6-b7fa-a34d8f5079b6
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 884 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--rapid-doctor.netlify.app%2Fpages%2Fother%2520pages%2Fpatient%2Fhistory%2520details%2520form.html%3Fappointment-id%3Dfc291eee-e94a-4ab6-b7fa-a34d8f5079b6&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x884&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--rapid-doctor.netlify.app/pages/other%20pages/patient/history%20details%20form.html?appointment-id=fc291eee-e94a-4ab6-b7fa-a34d8f5079b6)

**Comment by deepikasrm5** [comment]
I changed that.

**Comment by Saranya-Ramesh-27** [comment]
It is showing correctly now.
