### ISSUE TITLE
Sign up page error.

### ISSUE THREAD

**Issue by Saranya-Ramesh-27** [fssa-batch3/deepika.sriram__web_project#9]
### Description of issue
In the password field, it is asking to enter the requested format but the format is not mentioned.
```
Path:      /pages/other%20pages/other%20pages/sign%20up%20page.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 884 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--rapid-doctor.netlify.app%2Fpages%2Fother%2520pages%2Fother%2520pages%2Fsign%2520up%2520page.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x884&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--rapid-doctor.netlify.app/pages/other%20pages/other%20pages/sign%20up%20page.html)

**Comment by deepikasrm5** [comment]
I included the format of how the password should be...I hope it's working. please check it

**Comment by Saranya-Ramesh-27** [comment]
I checked. Now the format is visible.
